@startuml request-flow

skinparam activity {
  roundCorner 15
  FontColor          #fff
  FontSize           14
  BackgroundColor    #0090D5
  BorderColor        #14639c
  ArrowColor         #333
}

(*) --> "发起请求"

if "transformRequestData ?" then
  -right->[Yes] "requestData = transformRequestData(requestData)"
  --> ===TRANSREQ===
else
  -->[No] ===TRANSREQ===
endif

if "requestHandler ?" then
  -left->[No] "对 requestUrl 发出请求\n携带参数 requestData"
  --> ===RESPONSE===
else
  -->[Yes] "requestHandler(requestData)"
  --> ===RESPONSE===
endif

if "validateResponse(response) 验证通过"
  -->[No] "resolveRequestErrorMessage(response) \n获取错误信息并显示"
  -->(*)
else
  -->[Yes] "获取到原始响应数据 responseData"
  if "transformResponseData ?" then
    -right->[No] "直接使用 responseData"
    --> ===TRANS_RES===
  else
    -->[Yes] "responseData = transformResponseData(responseData)"
    --> ===TRANS_RES===
  endif
endif

--> "使用 contentDataMap 映射 responseData\n生成最终数据 contentData"

if "使用自定义 slot ?" then
  -->[No] "渲染表格视图"
  -->(*)
else
  -->[Yes] "挂载在 slot-scope 的 content-data "
  -->(*)
endif

@enduml
